"""add image_url to messages

Revision ID: e8f1eafcbdff
Revises: 3f40af0800e5
Create Date: 2026-06-23 00:09:39.155590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f1eafcbdff'
down_revision: Union[str, Sequence[str], None] = '3f40af0800e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
